---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-linters
    gate:
      jobs:
        - otc-tox-pep8
        - tox-linters-ansible-2.9
        - tox-linters-ansible-2.10
