telegraf_port: 8080
extra_parameters: |
    location / {
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
    }
    location /lb/telegraf {
        proxy_pass         http://192.168.1.1/telegraf;
        proxy_set_header   Host $host;
    }
    location /lbfail {
        proxy_pass         http://192.168.10.1/telegraf;
        proxy_set_header   Host $host;
    }
    location /as {
        proxy_pass         http://192.168.5.1/telegraf;
        proxy_set_header   Host $host;
    }
    location /smn {
        proxy_pass         http://192.168.5.1/smn;
        proxy_set_header   Host $host;
    }
