terraform_workspace: temp
scenario_name: csm_controller
key_path: /tmp/data
cloud_name: "{{ lookup('env', 'OS_CLOUD') }}"
cloud_config: /tmp
swift_operation: fetch
swift_container: csm
swift_object: lb_monitoring_inventory
key_name: infra-key

#vpc a nodes list
vpc_a_nodes: [
  {ip: 192.168.200.10, name: instance_1_eu-de-01},
  {ip: 192.168.200.11, name: instance_2_eu-de-01},
  {ip: 192.168.200.12, name: instance_3_eu-de-01},
  {ip: 192.168.200.13, name: instance_1_eu-de-02},
  {ip: 192.168.200.14, name: instance_2_eu-de-02},
  {ip: 192.168.200.15, name: instance_3_eu-de-02},
  {ip: 192.168.200.16, name: instance_1_eu-de-03},
  {ip: 192.168.200.17, name: instance_2_eu-de-03},
  {ip: 192.168.200.18, name: instance_3_eu-de-03}]
