---
- name: Prepare controller variables
  import_playbook: prepare_variables.yaml
  vars:
    scenario_name: >
      csm_controller
      as_monitoring

- name: Prepare variables
  hosts: localhost
  vars_files:
    - ./vars/csm_controller.yaml
    - ./vars/as_monitoring.yaml
  tasks:
    - name: Register hosts
      add_host:
        name: as_host
        ansible_host: "{{ as_monitoring.as_instance_ip }}"
        ansible_ssh_user: linux
        ansible_ssh_private_key_file: "{{ csm_controller.controller_key }}"
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ csm_controller.csm_controller_fip }}
          -i {{ csm_controller.controller_key }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null'
          -o PasswordAuthentication=no

- name: Start test
  hosts: as_host
  become: yes
  vars:
    script_path: /tmp/check_cpu_load_status.sh
  tasks:
    - name: Schedule load script status check  # noqa 301 305
      shell: "{{ script_path }}"
