---
- name: Prepare key and variables for scenario
  hosts: localhost
  environment:
    OS_CLOUD: "{{ lookup('env', 'CSM_CLOUD') | default('csm', True) }}"
  vars:
    key_path: /tmp/data
    key_name: infra-key
  tasks:
    - name: Obtain key for connection
      swift_client:
        state: "{{ swift_operation }}"
        container: "{{ swift_container }}"
        object_name: machine_key
      register: key

    - name: Save key for connection
      copy:
        content: "{{ key.object.content }}"
        dest: "{{ key_path }}/csm_key"
        mode: 0600

    - name: Swift get object
      swift_client:
        state: "{{ swift_operation }}"
        container: "{{ swift_container }}"
        object_name: infra_eips
      register: wtcr

    - name: facts
      set_fact:
        watchers_eips: "{{ (wtcr.object.content | from_yaml).watchers_eips | replace('-','_') }}"

    - name: Register VPC_A watcher
      add_host:
        name: vpc_a_watcher
        groups: watchers
        ansible_host: "{{ watchers_eips.watcher_eu_de_01 }}"
        ansible_ssh_user: linux
        ansible_ssh_private_key_file: "{{ key_path }}/csm_key"

- name: Ping hosts, normal packets
  hosts: vpc_a_watcher
  vars:
    metric_name: csm_vpc_ping.64
  tasks:
    - name: Measure latency
      script: >
        ping.py --metric_name "{{ metric_name }}"
        --hosts "{{ vpc_a_nodes }}"
      args:
        executable: "/usr/bin/python3"
      register: serialized_metrics

    - name: Register metrics
      set_fact:
        metrics: "{{ serialized_metrics.stdout }}"

- name: Send metrics to graphite
  hosts: localhost
  tasks:
    - name: Send metrics
      script: >
        send_metrics.py "{{ hostvars.vpc_a_watcher.metrics }}"
      args:
        executable: "/usr/bin/python3"

- name: Ping hosts, large packets 1500
  hosts: vpc_a_watcher
  vars:
    metric_name: csm_vpc_ping.1500
  tasks:
    - name: Measure latency
      script: >
        ping.py --metric_name "{{ metric_name }}"
        --hosts "{{ vpc_a_nodes }}"
        --packet_size 1492
      args:
        executable: "/usr/bin/python3"
      register: large_serialized_metrics

    - name: Register metrics
      set_fact:
        large_metrics: "{{ large_serialized_metrics.stdout }}"

- name: Send metrics to graphite
  hosts: localhost
  tasks:
    - name: Send metrics
      script: >
        send_metrics.py "{{ hostvars.vpc_a_watcher.large_metrics }}"
      args:
        executable: "/usr/bin/python3"
