---
- name: Prepare key and variables for scenario
  hosts: localhost
  vars:
    key_path: /tmp/data
    key_name: infra-key
  tasks:
    - name: Obtain key for connection
      script: >
        obs_cli.py
        --output "{{ key_path }}"
        --key "{{ key_name }}"

    - name: Swift get object
      swift_client:
        state: "{{ swift_operation }}"
        container: "{{ swift_container }}"
        object_name: infra_eips
      register: result

    - name: facts
      set_fact:
        watchers_eips: "{{ (result.object.content | from_yaml).watchers_eips | replace('-','_') }}"

    - name: Register VPC_B watcher
      add_host:
        name: vpc_b_watcher
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no
          -o IdentityFile="{{ key_path }}/{{ key_name }}"
          -o User=linux
          -o PasswordAuthentication=no
          -o StrictHostKeyChecking=no
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ watchers_eips.watcher_eu_de_01_vpc_b }}
          -i {{ key_path }}/{{ key_name }}'
