---
- name: Prepare controller variables
  import_playbook: prepare_variables.yaml
  vars:
    scenario_name: >
      csm_controller
      hdd_monitoring

- name: Prepare variables
  hosts: localhost
  vars_files:
    - ./vars/csm_controller.yaml
    - ./vars/hdd_monitoring.yaml
  tasks:
    - name: Register nodes
      add_host:
        name: "{{ item }}"
        groups: hdd_hosts
        ansible_ssh_common_args: >
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand='ssh -W %h:%p
          -q linux@{{ csm_controller.csm_controller_fip }}
          -i {{ csm_controller.controller_key }}
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null'
          -o PasswordAuthentication=no
      loop: "{{ hdd_monitoring.hdd_ecs_local_ips }}"

- name: Start test
  hosts: hdd_hosts
  become: yes
  vars:
    devices:
      sata: /dev/vdb
      sas: /dev/vdc
      ssd: /dev/vdd
  tasks:
    - name: Create big files on all devices every 5 minutes  # noqa 301 305
      shell: >
        /bin/dd if=/dev/urandom of="/mnt/{{ item.key }}/bigfile"
        bs=1000000 count=1000 oflag=dsync
      with_items: "{{ lookup('dict', devices) }}"
