---
- name: Gather metrics
  hosts: localhost
  environment:
    OS_CLOUD: "{{ lookup('env', 'CSM_CLOUD') | default('csm', True) }}"
  tasks:
    - name: Swift get object
      swift_client:
        state: "{{ swift_operation }}"
        container: "{{ swift_container }}"
        object_name: lb_monitoring
      register: result

    - name: facts
      set_fact:
        elb_address: "{{ (result.object.content | from_yaml).loadbalancer_private_ip }}"

    - name: Get metrics from loadbalancer (http listener)
      lb_load_monitoring:
        target_address: "{{ elb_address }}"
        protocol: http
        protocol_port: 80
        interface: internal
        listener_type: http

    - name: Get metrics from loadbalancer (https listener)
      lb_load_monitoring:
        target_address: "{{ elb_address }}"
        protocol: https
        protocol_port: 443
        interface: internal
        listener_type: https

    - name: Get metrics from loadbalancer (tcp listener)
      lb_load_monitoring:
        target_address: "{{ elb_address }}"
        protocol: http
        protocol_port: 3333
        interface: internal
        listener_type: tcp
