---
- name: Gather metrics
  hosts: localhost
  tasks:
    - name: Swift get object
      swift_client:
        state: "{{ swift_operation }}"
        container: "{{ swift_container }}"
        object_name: "{{ swift_object }}"
      register: result

    - name: facts
      set_fact:
        elb_address: "{{ (result.object.content | from_yaml).loadbalancer_public_ip }}"

    - name: Get metrics from loadbalancer
      lb_load_monitoring:
        target_address: "{{ elb_address }}"
