---
- name: Check csm utils
  hosts: localhost
  become: yes
  tasks:
    - name: Install PIP3
      apt:
        name:
          - python3-setuptools
          - python3-pip

    - name: Install csm-test-utils
      pip:
        executable: pip3
        name: csm-test-utils

- name: Gather metrics
  hosts: localhost
  become: yes
  vars:
    lb_load: /usr/bin/python3 -m csm_test_utils lb_load
    target: "--target http://{{ elb_address }}"
  tasks:
    - name: Get metrics from loadbalancer  # noqa 301 305
      command: "{{ lb_load }} {{ target }} {{ environment }} {{ zone }}"
