---
- name: Gather metrics
  hosts: localhost
  vars:
    lb_load: /usr/bin/python3 -m csm_test_utils lb_load
    target: "--target http://{{ elb_address }}"
  tasks:
    - name: Get metrics from loadbalancer  # noqa 301 305
      command: "{{ lb_load }} {{ target }}"
